# Generated by Django 5.1.1 on 2024-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done')], default='to do', max_length=50),
        ),
    ]
